runtime: nodejs
env: flex

env_variables:
  DB_USER: root
  DB_PASS: 111111
  DB_NAME: db1
  CLOUD_SQL_CONNECTION_NAME: apinode-266411:asia-southeast1:mysql01

beta_settings:
  cloud_sql_instances: apinode-266411:asia-southeast1:mysql01


